---
name: parallel
version: '1.20'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 4b908cef352d601d80978a9fe3e2a09210e7fc00
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
